// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SheeDrive/internal/dao/internal"
)

// internalArticleImagesDao is internal type for wrapping internal DAO implements.
type internalArticleImagesDao = *internal.ArticleImagesDao

// articleImagesDao is the data access object for table article_images.
// You can define custom methods on it to extend its functionality as you wish.
type articleImagesDao struct {
	internalArticleImagesDao
}

var (
	// ArticleImages is globally public accessible object for table article_images operations.
	ArticleImages = articleImagesDao{
		internal.NewArticleImagesDao(),
	}
)

// Fill with you ideas below.
