// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SheeDrive/internal/dao/internal"
)

// internalCarDetailDao is internal type for wrapping internal DAO implements.
type internalCarDetailDao = *internal.CarDetailDao

// carDetailDao is the data access object for table car_detail.
// You can define custom methods on it to extend its functionality as you wish.
type carDetailDao struct {
	internalCarDetailDao
}

var (
	// CarDetail is globally public accessible object for table car_detail operations.
	CarDetail = carDetailDao{
		internal.NewCarDetailDao(),
	}
)

// Fill with you ideas below.
