// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SheeDrive/internal/dao/internal"
)

// internalDealerDao is internal type for wrapping internal DAO implements.
type internalDealerDao = *internal.DealerDao

// dealerDao is the data access object for table dealer.
// You can define custom methods on it to extend its functionality as you wish.
type dealerDao struct {
	internalDealerDao
}

var (
	// Dealer is globally public accessible object for table dealer operations.
	Dealer = dealerDao{
		internal.NewDealerDao(),
	}
)

// Fill with you ideas below.
