// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"SheeDrive/internal/dao/internal"
)

// internalSwiperDao is internal type for wrapping internal DAO implements.
type internalSwiperDao = *internal.SwiperDao

// swiperDao is the data access object for table swiper.
// You can define custom methods on it to extend its functionality as you wish.
type swiperDao struct {
	internalSwiperDao
}

var (
	// Swiper is globally public accessible object for table swiper operations.
	Swiper = swiperDao{
		internal.NewSwiperDao(),
	}
)

// Fill with you ideas below.
